### ISSUE TITLE
Bad iterator access in platform.cpp

### ISSUE THREAD

**Issue by mapron** [trytouca/touca-cpp#122]
## Description

When I run test suite, I getting invalid iterator access on platform.cpp:95

## Environment

Windows, x64, MSVC 2019 x64, touca-cpp-1.5.1

## Steps To Reproduce

Compile For Debug config in Cmake, run test suite. eventually it crashes.

## Expected Behavior

It should not crash.

**Comment by mapron** [comment]
I will create a patch for this

**Comment by ghorbanzade** [comment]
Thank you so much for this first contribution! Patch was merged. Looking good.
