### ISSUE TITLE
Translation Units in `src` are compiled with `-std=c++14` by default

### ISSUE THREAD

**Issue by ghorbanzade** [trytouca/touca-cpp#124]
## Description

Generated `compile_commands` reveal that translation units in `src` are compiled with `-std=c++14` when user does not explicitly set `CMAKE_CXX_STANDARD`. This is surprising because we set `CMAKE_CXX_STANDARD` to 11 if this macro is not already defined by user. See https://github.com/trytouca/touca-cpp/blob/main/CMakeLists.txt#L34-L37.

## Environment

Behavior appears irrelevant to the choice of OS, compiler, and CMake generator. `-std=c++14` confirmed both on macOS and Linux for the latest code in `main`.

## Steps To Reproduce

Run `./build.sh --all` to build components. Check `local/build/compile_commands.json` and grep for `-std=c++14`

## Expected Behavior

We think the correct flag should be `-std=c++11`.

**Comment by mapron** [comment]
Core issues was cxx_aggregate_default_initializers  cmake feature which enabled std=c++14.
